# Generated by Django 6.0 on 2025-12-16 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastseen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
