# Generated by Django 6.0 on 2025-12-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_lastseen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lastseen',
            new_name='last_seen',
        ),
    ]
