# Generated by Django 6.0 on 2025-12-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_lastseen_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_chat_active',
            field=models.BooleanField(default=False),
        ),
    ]
