# Generated by Django 6.0 on 2025-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_chat_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileimage',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
