# Generated by Django 6.0 on 2025-12-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
    ]
